### ISSUE TITLE
Global compilation cache

### ISSUE THREAD

**Issue by galvanopus** [excelsior-oss/excelsior-jet-maven-plugin#15]
Consider we are using some fat third-party library in several projects. One project compilation can take about 1 hour and most of this time is spent on a fat library compilation. Having global compilation cache for such library will significantly decrease compilation time.

**Comment by fly-georg** [comment]
I got the same problem - is there any plan for the multi-component feature, or using DLL's somehow?

**Comment by pjBooms** [comment]
Yes, there is a plan to support multi-component model. Moreover, we are planning to support static libraries feature. So you will be able to compile your dependencies as static libraries and re-use them for compilation of different projects. And the plugin will support this model too (resulting in significant project recompilation time reduction).

**Comment by pjBooms** [comment]
We have implemented incremental builds in 64-bit versions of Excelsior JET 15.
During the implementation we thought about ability of sharing compilation cache (project database) between several projects but finally decided to not implement this. The reason is that project dependencies are optimised specially for the current project and the optimisations are hardly shareable between several projects. 
On the other hand we are going to provide an option in the plugin to set the location of the project database for the current project, and theoretically you can set it to the same value for several projects but it is not guarantied that results of compilations of a common library for one project will be reused for another but you may try. Please let us know what you think.

**Comment by galvanopus** [comment]
Could you clarify a bit more?

Let's we have Project A and Project B.
Project A depends on lib1.jar and lib2.jar.
Project B depends on lib1.jar and lib3.jar.

Does compiling lib1.jar for these 2 projects provide different results?

**Comment by pjBooms** [comment]
>>Does compiling lib1.jar for these 2 projects provide different results?
Yes, it can. lib1.jar can be optimized differently for those projects. 
However to save time you can (temporally) point the second project PDB location to the first project PDB location (or manually copy the PDB from first project to the PDB of the second). The compiler will try to reuse everything that is possible from compilation of the first project then. 

I think about some kind of automation of the process above. Now we have `<pdb>` section in the plugin and I think to add a parameter to it, say `<tryCopyFrom>'. With this parameter the plugin will automatically copy the referenced PDB for a clean build. Once the project's own PDB is created referenced PDB won't be used for subsequent compilations.

**Comment by galvanopus** [comment]
Thanks, sounds good. I am trying to dig into the issue, so there are 2 more questions on `tryCopyFrom`:

1. How the compilation time will be reduced by using `tryCopyFrom`? What steps will be omitted? How JET is going to determine which parts can be used?
2. Will the final compilation result be the same with `tryCopyFrom` and without it? If no, what could be the difference?

**Comment by pjBooms** [comment]
>>How the compilation time will be reduced by using tryCopyFrom

If you have many shared dependencies with the referenced project the most of the classes of shared dependencies won't be compiled for the first compilation of the project or after `jet:clean`

>>Will the final compilation result be the same with tryCopyFrom and without it?

Yes, it must be so.

**Comment by galvanopus** [comment]
Thanks. I have some more questions, but first I would like to perform some research.
